"use client";
import { useMemo,useState } from "react";
type Need="予約"|"見積"|"急ぎ"|"質問"|"折り返し";
type Status="受付"|"対応中"|"見積・予約"|"受注";
type Lead={id:number;name:string;need:Need;detail:string;status:Status;value:number};
const needs:Need[]=["予約","見積","急ぎ","質問","折り返し"];
export default function RecoveryDemo(){
 const [screen,setScreen]=useState<"customer"|"dashboard">("customer"),[need,setNeed]=useState<Need>("予約"),[name,setName]=useState(""),[detail,setDetail]=useState(""),[sent,setSent]=useState(false);
 const [leads,setLeads]=useState<Lead[]>([{id:1,name:"山田様",need:"見積",detail:"エアコン交換の見積希望",status:"受注",value:88000},{id:2,name:"佐藤様",need:"予約",detail:"土曜日の点検希望",status:"見積・予約",value:0},{id:3,name:"鈴木様",need:"折り返し",detail:"修理について相談",status:"対応中",value:0}]);
 const m=useMemo(()=>({missed:8,replies:leads.length+3,quotes:leads.filter(x=>x.status==="見積・予約"||x.status==="受注").length+2,wins:leads.filter(x=>x.status==="受注").length,revenue:leads.reduce((s,x)=>s+x.value,0)}),[leads]);
 function submit(e:React.FormEvent){e.preventDefault();setLeads(v=>[{id:Date.now(),name:name||"デモ顧客",need,detail:detail||"折り返し希望",status:"受付",value:0},...v]);setSent(true)}
 function advance(id:number){setLeads(v=>v.map(x=>x.id!==id?x:{...x,status:x.status==="受付"?"対応中":x.status==="対応中"?"見積・予約":"受注",value:x.status==="見積・予約"?55000:x.value}))}
 return <main className="recoveryApp"><header className="recoveryTop"><a href="/" className="recoveryBrand">WaSanDo <small>取りこぼし売上回収</small></a><div><button className={screen==="customer"?"on":""} onClick={()=>setScreen("customer")}>顧客画面</button><button className={screen==="dashboard"?"on":""} onClick={()=>setScreen("dashboard")}>店舗画面</button></div></header>
 {screen==="customer"?<section className="customerDemo"><p className="eyebrow">MISSED CALL RECOVERY｜DEMO</p><h1>お電話ありがとうございます。</h1><p className="demoLead">ただいま電話に出ることができません。ご用件を選んでいただければ、担当者にすぐ伝わります。</p>
 {!sent?<form onSubmit={submit}><fieldset><legend>ご用件</legend><div className="needGrid">{needs.map(n=><button type="button" key={n} className={need===n?"selected":""} onClick={()=>setNeed(n)}>{n}</button>)}</div></fieldset><label>お名前<input value={name} onChange={e=>setName(e.target.value)} placeholder="例：山田 太郎"/></label><label>内容<textarea value={detail} onChange={e=>setDetail(e.target.value)} placeholder="例：エアコン交換の見積をお願いしたい"/></label><button className="sendLead">この内容を送る →</button></form>:<div className="sentBox"><strong>受付しました。</strong><p>担当者に内容を送りました。このデモでは「店舗画面」を開くと、今の問い合わせが即時に追加されています。</p><button onClick={()=>setScreen("dashboard")}>店舗画面で確認 →</button></div>}</section>
 :<section className="businessDemo"><div className="demoHead"><div><p className="eyebrow">RECOVERED REVENUE</p><h1>取りこぼしを、売上に戻す。</h1></div><button onClick={()=>setScreen("customer")}>＋ 顧客画面でテスト</button></div><div className="metricGrid"><div><small>不在着信</small><strong>{m.missed}</strong><span>件</span></div><div><small>顧客回答</small><strong>{m.replies}</strong><span>件</span></div><div><small>見積・予約</small><strong>{m.quotes}</strong><span>件</span></div><div><small>受注</small><strong>{m.wins}</strong><span>件</span></div><div className="money"><small>回収売上</small><strong>¥{m.revenue.toLocaleString()}</strong></div></div><div className="leadList"><div className="leadHeader"><strong>問い合わせ</strong><span>クリックで次の段階へ進められます</span></div>{leads.map(x=><button key={x.id} onClick={()=>advance(x.id)}><div><strong>{x.name}</strong><span>{x.need}｜{x.detail}</span></div><em>{x.status}</em><b>{x.value?("¥"+x.value.toLocaleString()):"→"}</b></button>)}</div><p className="demoNote">DEMO：数値は動作確認用です。実運用では電話/SMS等の接続、通知先、業種別文面、受注金額を設定します。</p></section>}</main>
}