export type Route = { id: "company"|"income"|"takeover"; no:string; label:string; promise:string; detail:string; steps:readonly string[] };
export type Offer = { name:string; forWhom:string; result:string; deliverable:string; cta:string };
export type SiteCopy = { nav:{routes:string;tools:string;contact:string}; eyebrow:string; title:string; lead:string; choose:string; startTitle:string; startLead:string; routes:readonly Route[]; toolsTitle:string; toolsLead:string; offers:readonly Offer[]; closing:string; closingText:string; consult:string };

export const content: Record<"ja"|"en"|"pl", SiteCopy> = {
ja:{nav:{routes:"自社の稼ぎを増やす",tools:"新しい収入をつくる",contact:"相談する"},eyebrow:"WASANDO 100",title:"どうすれば「次の100年も」\n稼ぎ続けられるか",lead:"今ある事業の収益を拡大し、新規収入源を追加する。安定した利益を生み続ける為に、柔軟に行動する。",choose:"今の出発点を選ぶ",startTitle:"今、どこにいますか？",startLead:"出発点が違えば、最初に動かす場所も違います。",routes:[
{id:"company",no:"01",label:"会社を経営している",promise:"今ある会社から、もっと継続的に利益を生み出す",detail:"現状を洗い出し、利益を取りこぼしている箇所、時間のかかる作業、眠っている技術・ノウハウを見つけ、利益拡大につなげる。",steps:["今の収益構造を把握する","利益を取りこぼしている箇所を発見し、改善する","繰り返し行う作業を見直し、削除・簡素化・自動化する","眠っている技術・ノウハウ・顧客基盤を収益化する","既存の強みから新規収入源をつくる"]},
{id:"income",no:"02",label:"新しい収入源をつくりたい",promise:"小さく始め、継続して稼ぐ仕組みに育てる",detail:"先に大きく作りません。需要を見つけ、最小の商品・サービスで入金を確認し、売れたものだけを仕組みにします。",steps:["需要を見つける","小さく売る","入金で確かめる","繰り返せる部分を自動化する","他市場・他言語へ広げる"]},
{id:"takeover",no:"03",label:"稼いでいる事業を手に入れたい",promise:"ゼロから始めず、すでに稼いでいる事業を手に入れ、さらに育てる",detail:"ゼロから顧客と信用を作る代わりに、すでに売上・顧客・技術・信用のある事業を探します。通常の買収だけでなく、後継者不在などによる低額譲渡や、象徴的な金額での譲渡も対象にします。",steps:["候補を探す","稼げる理由を確認する","残す仕組みを取り出す","古い負担を減らす","新しい収入を加える"]}],toolsTitle:"利益を増やす為に、何を買えるのか。",toolsLead:"診断だけで終わらせません。利益改善、新規収入、業務自動化、海外販売。目的に合わせて、実際に使える形まで作ります。",offers:[
{name:"利益改善診断",forWhom:"今の事業から、もっと利益を残したい",result:"収益構造を確認し、取りこぼし・無駄・改善余地を特定。最初に手を付ける場所を決める。",deliverable:"改善項目一覧＋優先順位＋実行案",cta:"利益改善を相談する"},
{name:"新規収入源設計",forWhom:"今ある強みから、別の売上をつくりたい",result:"技術・ノウハウ・顧客基盤から、販売可能な商品・サービス候補を作り、最小単位で市場に出す。",deliverable:"商品案＋対象顧客＋販売方法＋検証案",cta:"新しい収入を相談する"},
{name:"業務自動化",forWhom:"繰り返し作業に時間を取られている",result:"作業を削除・簡素化・自動化に分け、必要な部分を実際に動く仕組みにする。",deliverable:"業務整理＋自動化フロー＋実働ツール",cta:"自動化を相談する"},
{name:"海外販売支援",forWhom:"日本以外にも売上を広げたい",result:"商品・サービスを対象市場向けに調整し、言語だけでなく売り方まで現地向けに組み直す。",deliverable:"市場選定＋販売仕様＋現地向け販売素材",cta:"海外販売を相談する"}
],closing:"まず、どの稼ぎを動かすか。",closingText:"全部を変える必要はありません。最初に利益へつながる一か所を決め、そこから小さく動かします。",consult:"相談する"},
en:{nav:{routes:"3 starting points",tools:"Small tools",contact:"Talk to us"},eyebrow:"WASANDO 100",title:"How do you keep earning\nfor the next 100 years?",lead:"The objective is not merely to preserve a company. Strengthen what already earns, add new income, and reduce dependence on one person, customer, market or location.",choose:"Choose your starting point",startTitle:"Where are you starting from?",startLead:"Different starting points require different first moves.",routes:[
{id:"company",no:"01",label:"I run a company",promise:"Generate more durable profit from the business you already have",detail:"Find revenue leakage, weak margins, unnecessary manual work, owner dependence and underused know-how, then change the point with the clearest profit impact first.",steps:["Measure how the business earns","Fix profit leakage","Remove unnecessary human work","Create new income from existing strengths","Diversify customer, people and market dependence"]},
{id:"income",no:"02",label:"I want a new income stream",promise:"Start small and grow it into repeatable income",detail:"Do not build big first. Find demand, test the smallest sellable offer, confirm payment, then systemize only what actually sells.",steps:["Find demand","Sell something small","Validate with payment","Automate what repeats","Expand to other markets and languages"]},
{id:"takeover",no:"03",label:"I want to take over a business",promise:"Start with a business that already earns, then improve it",detail:"Instead of creating customers and trust from zero, assess existing revenue, customers, know-how and reputation, then decide what to preserve and what to change.",steps:["Find candidates","Verify why it earns","Extract what must remain","Remove legacy burden","Add new income"]}],toolsTitle:"What can you buy to increase profit?",toolsLead:"Not a report that ends with advice. Choose the objective and we build the usable result.",offers:[
{name:"Profit Improvement Review",forWhom:"Get more profit from the business you already run",result:"Find leakage, waste and the highest-impact improvement point.",deliverable:"Prioritized improvements + action plan",cta:"Discuss profit improvement"},
{name:"New Income Design",forWhom:"Turn existing strengths into another revenue stream",result:"Convert know-how, technology or customer access into a testable offer.",deliverable:"Offer + buyer + sales route + validation plan",cta:"Discuss new income"},
{name:"Workflow Automation",forWhom:"Reduce time spent on repetitive work",result:"Remove, simplify and automate repetitive work, then build what is needed.",deliverable:"Workflow redesign + working automation",cta:"Discuss automation"},
{name:"Overseas Sales",forWhom:"Create revenue outside your home market",result:"Adapt the offer and its sales method for a selected foreign market.",deliverable:"Market choice + sales specification + localized materials",cta:"Discuss overseas sales"}
],closing:"First, decide which earning engine to move.",closingText:"You do not need to transform everything at once. Choose the first point that can affect profit and start there.",consult:"Talk to us"},
pl:{nav:{routes:"3 punkty startu",tools:"Małe narzędzia",contact:"Porozmawiajmy"},eyebrow:"WASANDO 100",title:"Jak zarabiać nieprzerwanie\nprzez następne 100 lat?",lead:"Celem nie jest samo zachowanie firmy. Wzmacniamy to, co już zarabia, dodajemy nowe źródła przychodu i zmniejszamy zależność od jednej osoby, klienta, rynku lub miejsca.",choose:"Wybierz swój punkt startu",startTitle:"Z jakiego miejsca startujesz?",startLead:"Inny punkt startu oznacza inny pierwszy ruch.",routes:[
{id:"company",no:"01",label:"Prowadzę firmę",promise:"Więcej trwałego zysku z firmy, którą już masz",detail:"Szukamy utraconej sprzedaży, słabych marż, zbędnej pracy ręcznej, zależności od właściciela i niewykorzystanego know-how. Zaczynamy tam, gdzie efekt finansowy może być najszybszy.",steps:["Zmierz, jak firma zarabia","Usuń wycieki zysku","Ogranicz zbędną pracę ludzi","Zbuduj nowe przychody na obecnych mocnych stronach","Zmniejsz zależność od klientów, ludzi i jednego rynku"]},
{id:"income",no:"02",label:"Chcę nowe źródło dochodu",promise:"Zacznij mało i zbuduj powtarzalny dochód",detail:"Nie budujemy dużego produktu na początku. Najpierw popyt, najmniejsza oferta, realna płatność, a dopiero potem rozwój i automatyzacja tego, co się sprzedaje.",steps:["Znajdź popyt","Sprzedaj małą ofertę","Potwierdź popyt płatnością","Automatyzuj powtarzalne elementy","Wejdź na kolejne rynki i języki"]},
{id:"takeover",no:"03",label:"Chcę przejąć firmę lub biznes",promise:"Przejmij biznes, który już zarabia, i rozwijaj go dalej",detail:"Zamiast od zera zdobywać klientów i zaufanie, analizujemy istniejące przychody, klientów, technologię, know-how i reputację, a następnie oddzielamy to, co warto zachować, od tego, co trzeba zmienić.",steps:["Znajdź kandydatów","Sprawdź, dlaczego biznes zarabia","Wyodrębnij to, co trzeba zachować","Usuń stare obciążenia","Dodaj nowe źródła przychodu"]}],toolsTitle:"Co możesz kupić, aby zwiększyć zysk?",toolsLead:"Nie kończymy na raporcie. Wybieramy cel i budujemy rozwiązanie gotowe do użycia.",offers:[
{name:"Audyt poprawy zysku",forWhom:"Więcej zysku z obecnego biznesu",result:"Znajdujemy straty, zbędne koszty i punkt o największym wpływie na wynik.",deliverable:"Priorytety zmian + plan działania",cta:"Porozmawiaj o zysku"},
{name:"Projekt nowego dochodu",forWhom:"Nowe przychody z obecnych mocnych stron",result:"Zmieniamy know-how, technologię lub relacje z klientami w ofertę do przetestowania.",deliverable:"Oferta + klient + kanał sprzedaży + test",cta:"Porozmawiaj o dochodzie"},
{name:"Automatyzacja pracy",forWhom:"Mniej czasu na powtarzalne zadania",result:"Usuwamy, upraszczamy i automatyzujemy pracę, a następnie budujemy potrzebne rozwiązanie.",deliverable:"Nowy proces + działająca automatyzacja",cta:"Porozmawiaj o automatyzacji"},
{name:"Sprzedaż zagraniczna",forWhom:"Przychody poza rynkiem krajowym",result:"Dostosowujemy ofertę i sposób sprzedaży do wybranego rynku.",deliverable:"Rynek + model sprzedaży + lokalne materiały",cta:"Porozmawiaj o eksporcie"}
],closing:"Najpierw wybierzmy, który mechanizm zarabiania uruchomić.",closingText:"Nie trzeba zmieniać wszystkiego naraz. Wybieramy pierwszy punkt, który może wpłynąć na zysk, i od niego zaczynamy.",consult:"Porozmawiajmy"}
};