export type Route = { id: "company"|"income"|"takeover"; no:string; label:string; promise:string; detail:string; steps:readonly string[] };
export type SiteCopy = { nav:{routes:string;tools:string;contact:string}; eyebrow:string; title:string; lead:string; choose:string; startTitle:string; startLead:string; routes:readonly Route[]; toolsTitle:string; toolsLead:string; toolExamples:readonly string[]; closing:string; closingText:string; consult:string };

export const content: Record<"ja"|"en"|"pl", SiteCopy> = {
ja:{nav:{routes:"3つの入口",tools:"小さなツール",contact:"相談する"},eyebrow:"WASANDO 100",title:"どうすれば「次の100年も」\n稼ぎ続けられるか",lead:"会社を残すことではなく、稼ぐ力を残す。今ある利益を強くし、新しい収入をつくり、人や一つの市場への依存を減らします。",choose:"今の出発点を選ぶ",startTitle:"今、どこにいますか？",startLead:"出発点が違えば、最初に動かす場所も違います。",routes:[
{id:"company",no:"01",label:"会社を経営している",promise:"今ある会社から、もっと継続的に利益を生み出す",detail:"取りこぼし、利益率、人手、社長依存、眠っているノウハウを調べ、最短で利益に効く場所から変えます。",steps:["今の稼ぎを測る","利益が漏れている場所を直す","人が不要な仕事を減らす","既存の強みから別の収入をつくる","顧客・人・市場への依存を分散する"]},
{id:"income",no:"02",label:"新しい収入源をつくりたい",promise:"小さく始め、継続して稼ぐ仕組みに育てる",detail:"先に大きく作りません。需要を見つけ、最小の商品・サービスで入金を確認し、売れたものだけを仕組みにします。",steps:["需要を見つける","小さく売る","入金で確かめる","繰り返せる部分を自動化する","他市場・他言語へ広げる"]},
{id:"takeover",no:"03",label:"会社・事業を引き継ぎたい",promise:"すでに稼いでいる事業を引き継ぎ、さらに育てる",detail:"ゼロから顧客と信用を作る代わりに、すでにある売上・顧客・技術・信用を見極め、残すものと変えるものを分けます。",steps:["候補を探す","稼げる理由を確認する","残す仕組みを取り出す","古い負担を減らす","新しい収入を加える"]}],toolsTitle:"巨大なシステムではなく、必要な機能だけ。",toolsLead:"一つの仕事をする小さなツールを組み合わせます。各ツールは単独でも販売でき、ホワイトラベル・多言語を前提に設計します。",toolExamples:["需要検証","見込み客フォロー","Knowledge Capture","業務自動化","Content Localizer","Clip Generator","Performance Checker","海外販売支援"],closing:"まず、どの稼ぎを動かすか。",closingText:"全部を変える必要はありません。最初に利益へつながる一か所を決め、そこから小さく動かします。",consult:"相談する"},
en:{nav:{routes:"3 starting points",tools:"Small tools",contact:"Talk to us"},eyebrow:"WASANDO 100",title:"How do you keep earning\nfor the next 100 years?",lead:"The objective is not merely to preserve a company. Strengthen what already earns, add new income, and reduce dependence on one person, customer, market or location.",choose:"Choose your starting point",startTitle:"Where are you starting from?",startLead:"Different starting points require different first moves.",routes:[
{id:"company",no:"01",label:"I run a company",promise:"Generate more durable profit from the business you already have",detail:"Find revenue leakage, weak margins, unnecessary manual work, owner dependence and underused know-how, then change the point with the clearest profit impact first.",steps:["Measure how the business earns","Fix profit leakage","Remove unnecessary human work","Create new income from existing strengths","Diversify customer, people and market dependence"]},
{id:"income",no:"02",label:"I want a new income stream",promise:"Start small and grow it into repeatable income",detail:"Do not build big first. Find demand, test the smallest sellable offer, confirm payment, then systemize only what actually sells.",steps:["Find demand","Sell something small","Validate with payment","Automate what repeats","Expand to other markets and languages"]},
{id:"takeover",no:"03",label:"I want to take over a business",promise:"Start with a business that already earns, then improve it",detail:"Instead of creating customers and trust from zero, assess existing revenue, customers, know-how and reputation, then decide what to preserve and what to change.",steps:["Find candidates","Verify why it earns","Extract what must remain","Remove legacy burden","Add new income"]}],toolsTitle:"Not one huge system. Only the functions you need.",toolsLead:"Combine small tools that each do one useful job. Every tool is designed to work independently, white-labelled and multilingual.",toolExamples:["Demand Validator","Lead Follow-up","Knowledge Capture","Workflow Automation","Content Localizer","Clip Generator","Performance Checker","Export Support"],closing:"First, decide which earning engine to move.",closingText:"You do not need to transform everything at once. Choose the first point that can affect profit and start there.",consult:"Talk to us"},
pl:{nav:{routes:"3 punkty startu",tools:"Małe narzędzia",contact:"Porozmawiajmy"},eyebrow:"WASANDO 100",title:"Jak zarabiać nieprzerwanie\nprzez następne 100 lat?",lead:"Celem nie jest samo zachowanie firmy. Wzmacniamy to, co już zarabia, dodajemy nowe źródła przychodu i zmniejszamy zależność od jednej osoby, klienta, rynku lub miejsca.",choose:"Wybierz swój punkt startu",startTitle:"Z jakiego miejsca startujesz?",startLead:"Inny punkt startu oznacza inny pierwszy ruch.",routes:[
{id:"company",no:"01",label:"Prowadzę firmę",promise:"Więcej trwałego zysku z firmy, którą już masz",detail:"Szukamy utraconej sprzedaży, słabych marż, zbędnej pracy ręcznej, zależności od właściciela i niewykorzystanego know-how. Zaczynamy tam, gdzie efekt finansowy może być najszybszy.",steps:["Zmierz, jak firma zarabia","Usuń wycieki zysku","Ogranicz zbędną pracę ludzi","Zbuduj nowe przychody na obecnych mocnych stronach","Zmniejsz zależność od klientów, ludzi i jednego rynku"]},
{id:"income",no:"02",label:"Chcę nowe źródło dochodu",promise:"Zacznij mało i zbuduj powtarzalny dochód",detail:"Nie budujemy dużego produktu na początku. Najpierw popyt, najmniejsza oferta, realna płatność, a dopiero potem rozwój i automatyzacja tego, co się sprzedaje.",steps:["Znajdź popyt","Sprzedaj małą ofertę","Potwierdź popyt płatnością","Automatyzuj powtarzalne elementy","Wejdź na kolejne rynki i języki"]},
{id:"takeover",no:"03",label:"Chcę przejąć firmę lub biznes",promise:"Przejmij biznes, który już zarabia, i rozwijaj go dalej",detail:"Zamiast od zera zdobywać klientów i zaufanie, analizujemy istniejące przychody, klientów, technologię, know-how i reputację, a następnie oddzielamy to, co warto zachować, od tego, co trzeba zmienić.",steps:["Znajdź kandydatów","Sprawdź, dlaczego biznes zarabia","Wyodrębnij to, co trzeba zachować","Usuń stare obciążenia","Dodaj nowe źródła przychodu"]}],toolsTitle:"Nie jeden ogromny system. Tylko potrzebne funkcje.",toolsLead:"Łączymy małe narzędzia, z których każde wykonuje jedno użyteczne zadanie. Każde może działać samodzielnie, jako white label i w wielu językach.",toolExamples:["Walidacja popytu","Follow-up leadów","Knowledge Capture","Automatyzacja pracy","Lokalizacja treści","Clip Generator","Kontrola wyników","Wsparcie eksportu"],closing:"Najpierw wybierzmy, który mechanizm zarabiania uruchomić.",closingText:"Nie trzeba zmieniać wszystkiego naraz. Wybieramy pierwszy punkt, który może wpłynąć na zysk, i od niego zaczynamy.",consult:"Porozmawiajmy"}
};